### ISSUE TITLE
infinite for cycle

### ISSUE THREAD

**Issue by avasapollo** [andygrunwald/vdf#6]
Ciao Andy, I want to start with thanks for the library.
I found out a bug, in some case if the file vdf is corrupted the library is in stuck in infinite cycle where it try to looking for `"` to close.
Example
 ```
 "SaveFile"
{
	"timestamp"		"2020-12-21 16:16:07"
	"team1"		"team_Ciccio"
	"team2"		"team_Pasticcio"
	"map"		"de_mirage"
	"round"		"6"
	"FirstHalfScore"
	{
		"team1"		"0"
		"team2"		"6"
	}
	"History"
	{
		"NumConsecutiveCTLoses"		"7"
		"LoserBonus"		"3400"
		"LoserMostRecentTeam"		"CT"
	}
	"RoundResults"
	{
		"round
 ```
 in this case the library it is stuck forever.
 Tomorrow I would like to try to fix that, do you accept PR?
 Thanks

**Comment by andygrunwald** [comment]
Hey Andrea,
Yeah! I would be very happy to accept a PR for this.
Really great would be a unit test to cover this.

Let me know if you need support. Happy to help.

Andrea Vasapollo <notifications@github.com> schrieb am Mo. 21. Dez. 2020 um
18:06:

**Comment by avasapollo** [comment]
ok cool I ll try to take a look tomorrow ;)
Thanks

**Comment by avasapollo** [comment]
Ciao @andygrunwald I created the PR if you wan to take a look ;)

**Comment by andygrunwald** [comment]
Hey @ avasapollo,
thanks a lot for this quality https://github.com/andygrunwald/vdf/pull/9
I merged it. Furthermore, I updated the CI system to GitHub actions to cover the latest Go versions.

What is your use-case for vdf? Are you using it at @faceit?

**Comment by avasapollo** [comment]
Ciao @andygrunwald , yes I am using that on faceit. 
I ll write you a private email if you are interested let me know
